### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by lukesneeringer** [googleapis/go-type-adapters#2]
- [x] Merge initial types (#1)
- [x] Add `CONTRIBUTING` and `CODE_OF_CONDUCT`. (#3)
- [x] Add GitHub Action workflow. (#4)
- [x] Set up branch protection
- [x] Configure Renovate (#5)
- [x] Add `sync-repo-settings.yaml`.
- [x] Run internal OSS linter.
